#include "shipTypes/Amphibious.cpp"
#include "shipTypes/Battleship.cpp"
#include "shipTypes/Corvette.cpp"
#include "shipTypes/Cruiser.cpp"
#include "shipTypes/Destroyer.cpp"
#include "shipTypes/Frigate.cpp"
#include "shipTypes/SuperShip.cpp"
